### ISSUE TITLE
Issue with building the executable

### ISSUE THREAD

**Issue by Alim-faraji** [HighDimensionalEconLab/VarianceComponentsHDFE.jl#12]
There is a problem with building the executable. I guess it is related to Artifacts. When I try to locally compile, I get an error saying it's unable to install "huge_nocontrols_pruned" from Artifacts.toml file. 
Until we have this issue solved, we can't share the executable with others, as the github actions fail too. So I guess it's a high priority issue. I like to help too, so let me know if we could collaborate on it.

**Comment by jlperla** [comment]
Just to summarize my suggested solution:
- move the `Artifacts.toml` inside of the `benchmark`.  If that makes things work great for the building of the executable/etc. then lets leave it there and continue on a new issue separately for teh benchmarking.
