### ISSUE TITLE
Getting benchmarking files downloaded

### ISSUE THREAD

**Issue by jlperla** [HighDimensionalEconLab/VarianceComponentsHDFE.jl#16]
Assuming that #12 fixes things with the `Artifacts.toml` in the bernchmark folder.  We should either see if we can get it working cleanly there or replace it with just using the `curl`.  It isn't worth that much effort if it is a problem

@paulcorcuera  Maybe you can just change this liner: https://github.com/HighDimensionalEconLab/VarianceComponentsHDFE.jl/blob/main/benchmark/prepare_benchmark_data.jl#L6

to be
```julia
artifacts_path = joinpath(pkgdir(VarianceComponentsHDFE), "benchmark/Artifacts.toml")
```
And see if it works?

**Comment by jlperla** [comment]
But if that doesn't work, then lets remove the artifacts and we can just use `curl` into the data folders.  I can discuss the options there after.

**Comment by paulcorcuera** [comment]
It worked. I'm clossing this issue now.
