### ISSUE TITLE
Update readme.md with installation and usage instructions

### ISSUE THREAD

**Issue by jlperla** [HighDimensionalEconLab/VarianceComponentsHDFE.jl#2]
: it should be a idiot-proof copy paste. "Instructions for Windows", "Instructions for OSX", etc. As little text as possibe with as much brainless copy and paste.

The current one: https://github.com/HighDimensionalEconLab/VarianceComponentsHDFE.jl#using-the-executable should be redone compoletely since it is not copy/paste and there shouldn't be any "thinking" involved in following the instructions. The instructions to follow should also use the test.csv built into the binary in #84 so it really is a copy/paste to do that exact setup.

Finallly, what is written in the description of https://github.com/HighDimensionalEconLab/VarianceComponentsHDFE.jl#using-the-executable should be moved into a subsection later on which describes the executable arguments. Or you could see if the current vchdfe --help output is solid enough? If so, then maybe copy/paste that whole output into the readme to show people how to get help, and let them read what it says.

@paulcorcuera You can put on your "applied micro" hat when going through this to make sure it wouldn't seem scary to someone in that field.

**Comment by jlperla** [comment]
What I envision for the "Manual Setup" is that we would give a sequence of powershell or bash commands.  The only thinking that the user should have is that they would choose where they want to install it.

So for windows, for example, I would have it as something like:

# Windows Manual Installation
1. Choose where you want to install the package, open up a powershell terminal, and go to that location;
2. Install the latest version by executing
```bash
wget -qO- https://github.com/HighDimensionalEconLab/VarianceComponentsHDFE.jl/releases/download/v0.2/vchdfe-windows-latest.tar.gz | tar -xzv
```
3. Optional: Add the `bin` within this your system path  (@Alim-faraji  see more below)
```bash
setx PATH %PATH%;C:\bin\vchdfe\bin
```
4. Test using the example testfile
```bash
vchdfe --data=bin/test.csv
```

================
NOTE:  I would much rather this be automatic so they don't need manually change this.  Mabye there is a way to do it like
```bash
set NEWPATH = %PATH%;%HOWEVERYOUGETCURRENTDIRECTORY%\vchdfe\bin
setx PATH %NEWPATH%
```
Or probably something with the powershell `Get-Location` would be easier to copy/paste.

For ubuntu users, they will be more tech'd up, so you can tell them to modify their bash file.  Choose a reasonable default location such as just in the users diretory `~` so they can copy/paste.  See https://github.com/QuantEcon/lecture-source-jl#prerequisities for some text to copy/paste on how to edit the `.bashrc` that you could add.

**Comment by Alim-faraji** [comment]
Reminder for myself: make sure the changes to PATH are permanent.

**Comment by Alim-faraji** [comment]
Fix pipes in Windows instructions.
