### ISSUE TITLE
Improve Step 3 in MacOS instructions

### ISSUE THREAD

**Issue by paulcorcuera** [HighDimensionalEconLab/VarianceComponentsHDFE.jl#21]
I can see MacOS users getting lost here in Step 3 here : https://highdimensionaleconlab.github.io/VarianceComponentsHDFE.jl/dev/#MacOS. 

Is there a way to add bin to PATH without manually editing `.bash_profile`? If there's no other way then we should provide some steps on how to open and edit that.

**Comment by Alim-faraji** [comment]
I don't use OSX.

**Comment by paulcorcuera** [comment]
I see. I'll investigate further on this.
