### ISSUE TITLE
Fix Parsed Arguments in Executable

### ISSUE THREAD

**Issue by paulcorcuera** [HighDimensionalEconLab/VarianceComponentsHDFE.jl#26]
A student has noticed a bug with the executable. The error that is being thrown is the following:

`vchdfe connected_sample.csv --first_id 1 --second_id 3 --observation_id 4 --header --detailed_output_path "var_components.csv" --results_path "results.txt" --no_first_id_effects
present working directory is /Users/X/Documents/Econ 628/PS3/Data
ERROR: KeyError: key "first_id_effects" not found
Stacktrace:
 [1] getindex(::Dict{String,Any}, ::String) at ./dict.jl:467
 [2] real_main() at /Users/runner/work/VarianceComponentsHDFE.jl/VarianceComponentsHDFE.jl/src/VarianceComponentsHDFE.jl:134
 [3] julia_main() at /Users/runner/work/VarianceComponentsHDFE.jl/VarianceComponentsHDFE.jl/src/VarianceComponentsHDFE.jl:111
 [4] julia_main() at ./none:29`

My first guess is that this has to do with the arguments [here](https://github.com/HighDimensionalEconLab/VarianceComponentsHDFE.jl/blob/main/src/VarianceComponentsHDFE.jl#L28-L107). In particular, the argument asks for `no_first_id_effects` but in the main function [here](https://github.com/HighDimensionalEconLab/VarianceComponentsHDFE.jl/blob/main/src/VarianceComponentsHDFE.jl#L134) it is looking for `first_id_effects` instead. I think it should suffice to change these lines:

1. `    first_id_effects = parsed_args["first_id_effects"] ` with  `    first_id_effects = parsed_args["no_first_id_effects"] == 1 ?  0: 1 `
2.  `    cov_effects = parsed_args["cov_effects"]` with `    cov_effects = parsed_args["no_cov_effects"] == 1 ?  0: 1`

Then we must run the build again and check that that command runs now (you could use our own test.csv or any other file to do this check).

**Comment by Alim-faraji** [comment]
The error in the interface is fine now. But we can't still run the executable with `--no_first_id_effects` (i.e. not calculating first id effects). I remember we decided before to postpone it and compute both effects for now. I think I can work on it, but I'm not what is its priority. (edited)

**Comment by Alim-faraji** [comment]
There are some other parts of the code that need further fixings. 

- [x] It was not right.  https://github.com/HighDimensionalEconLab/VarianceComponentsHDFE.jl/blob/50349b3368c524182b3a7b952300a160b10c7503/src/VarianceComponentsHDFE.jl#L200-L202
I changed it to 
`        y_output = y
        first_id_output = first_id
        second_id_output = second_id`

- [ ] When I ran the executable on the test file with `--write_detailed_CSV`, there was an error on 
https://github.com/HighDimensionalEconLab/VarianceComponentsHDFE.jl/blob/50349b3368c524182b3a7b952300a160b10c7503/src/VarianceComponentsHDFE.jl#L227 saying it can't write `nothing` to a CSV file and we have to change it to `missing` or something.

**Comment by Alim-faraji** [comment]
We have to check other arguments of the command line too. Do you know of any automatic process that can handle it, maybe something like unit tests? Or we need to manually test all the arguments.

**Comment by paulcorcuera** [comment]
I am not aware of any automatic process. I think it will have to be a manual process to work this out.
