### ISSUE TITLE
New version of Julia Code & Executable

### ISSUE THREAD

**Issue by paulcorcuera** [HighDimensionalEconLab/VarianceComponentsHDFE.jl#28]
The next release of the Executable must fix the following things: 

- [x] Rename `observation_id ` arguments in the executable and code. The new name will be `outcome_id ` instead. I believe I have commited changes to incorporate this, but may need a double check. 

- [x] Make sure the executable prints both the Plug in estimates as well as the Bias Corrected ones. I believe the change I made [here](https://github.com/HighDimensionalEconLab/VarianceComponentsHDFE.jl/blob/main/src/leave_out_correction.jl#L1013-L1016) would suffice. 

- [x] Make sure the default is to return all three variance components. Again, I think the change I made [here](https://github.com/HighDimensionalEconLab/VarianceComponentsHDFE.jl/blob/main/src/VarianceComponentsHDFE.jl#L47-L52) would suffice. 

- [x]  When we attempted to replicate Table 2 of [KSS](https://eml.berkeley.edu/~pkline/papers/KSS2020.pdf), we encountered a `DomainError`. In particular, this error appeared when we ran the Exact algorithm on column 3 of Table 2. This error originates from the `Krylov.cg` solver, and it is caused when the smallest eigenvalue of the Grounded Laplacian is very small (i.e. it is very close to positive semi definitive instead of positive definite). A solution to this problem was attempted a couple of months ago in this [PR](https://github.com/JuliaSmoothOptimizers/Krylov.jl/pull/204), but this change was not merged to the Krylov package.  Therefore, we need to fork the [Krylov](https://github.com/JuliaSmoothOptimizers/Krylov.jl) package where we replace this [line](https://github.com/JuliaSmoothOptimizers/Krylov.jl/blob/master/src/cg.jl#L111) by ` rNorm = sqrt(abs(γ_next))
`.  This should fix the error encountered. 

- [x]  Using the data in Column 3 of Table 2 in KSS, Raffa found an error when running the executable with the arguments `--first_id 1 --second_id 2 --observation_id 3 --write_results --write_detailed_CSV --detailed_output_path output.csv --results_path summary.txt`. The error encountered said `Error: A nothing value was found in column 8 and it is not a printable value`. Let's see if we are able to run that line just fine. 

- [x]  We must ensure that we can fully replicate Table 2 in KSS using the new version of the Executable. We must be able to run both the JLA and Exact Algorithm (and check that after the changes, the results of the executable are rather close to the results in the paper).

- [x]  We must fix some minor details in the documentation of the package. The numbered lists must be showing correctly. I have ommited any steps where the users require `wget`, so let's check whether it is simple to follow the new steps. 

- [ ]  Put some instructions in the Package documentations that don't necessarily require users to install VsCode and Github Desktop. Something that could be done from any Julia REPL. 

- [x]  Test the executable (using test.csv so it is faster) with different combinations of our options and see if there are no hidden bugs.

**Comment by Alim-faraji** [comment]
Do you want to print the Plug-in estimates and the Bias Corrected ones on the std output, or should we print them in the detailed output txt file?

**Comment by Alim-faraji** [comment]
In case we want to print them on the std output, your changes suffice. Thanks! I'm just gonna add a conditional statement before the printing statement so that it prints only if the print_level is not zero. 
https://github.com/HighDimensionalEconLab/VarianceComponentsHDFE.jl/blob/ecc06e09936f43f0e888660c0de07ce2ecfb907f/src/leave_out_correction.jl#L55

**Comment by paulcorcuera** [comment]
> In case we want to print them on the std output, your changes suffice. Thanks! I'm just gonna add a conditional statement before the printing statement so that it prints only if the print_level is not zero.
> https://github.com/HighDimensionalEconLab/VarianceComponentsHDFE.jl/blob/ecc06e09936f43f0e888660c0de07ce2ecfb907f/src/leave_out_correction.jl#L55

Yes! Right now the console shows the lines "Finding leave-out set; Plug in estimates" then it stops. The idea is that it also prints the bias corrected ones there, so you know the executable finished running (or is close to finishing).

**Comment by paulcorcuera** [comment]
I think Slack is down. Feel free to ask anything here!

**Comment by Alim-faraji** [comment]
Yeah, slack is down. I started the day by working on this issue.

**Comment by Alim-faraji** [comment]
I think the default for computing variances was fine before. It should be 
`action = :store_true`. 
So the default is false and it changes to true on action. 


Oh, I see. I recall that Raffa ran the executable and the .txt file was only printing the bias corrected component of the firm variance. We must make sure it stores all three. My guess was that something was going on with the default, but it seems that the options were defined correctly. Sorry

**Comment by Alim-faraji** [comment]
Why did you removed all the `wget` instructions?

**Comment by paulcorcuera** [comment]
> Why did you removed all the `wget` instructions?

Raffa had a hard time replicating that part following our docs. In particular, wget needs some other previous steps to be used in MacOS (e.g. see [here](https://www.howtogeek.com/281663/how-to-use-wget-the-ultimate-command-line-downloading-tool/#:~:text=macOS%20systems%20do%20not%20come,install%20wget%20in%20the%20Terminal.)).  Encountering some issues with the wget command might be a big deal for some users, so it might be easier  to simply just ask them to click a link and place the file where they want.

**Comment by Alim-faraji** [comment]
> I think the default for computing variances was fine before. It should be
> `action = :store_true`.
> So the default is false and it changes to true on action.
> 
> Oh, I see. I recall that Raffa ran the executable and the .txt file was only printing the bias corrected component of the firm variance. We must make sure it stores all three. My guess was that something was going on with the default, but it seems that the options were defined correctly. Sorry

Yes, I think the problem was with the printing. I remember I had the same issue but it was fixed in the new release of the executable.

**Comment by paulcorcuera** [comment]
> > I think the default for computing variances was fine before. It should be
> > `action = :store_true`.
> > So the default is false and it changes to true on action.
> > Oh, I see. I recall that Raffa ran the executable and the .txt file was only printing the bias corrected component of the firm variance. We must make sure it stores all three. My guess was that something was going on with the default, but it seems that the options were defined correctly. Sorry
> 
> Yes, I think the problem was with the printing. I remember I had the same issue but it was fixed in the new release of the executable.

I see. Thank you. I realized that Raffa was using a previous version of the executable at that time. I updated the links in the installation instructions to the latest version.

**Comment by paulcorcuera** [comment]
You can replicate `Domain error` by running this with the executable 
`vchdfe .\bin\old_All_VenetoCS_Leave1.csv --first_id 1 --second_id 2 --observation_id 3 --algorithm Exact --header --write_results --results_path summary2.txt `

In those leave-out datasets the outcome_id is the third column. I can send you the three files again to your email if you provide it to me (in case you weren't able to store them).

**Comment by Alim-faraji** [comment]
Yes, please send them to `alim.faraji@ubc.ca`.

**Comment by Alim-faraji** [comment]
Should I fork the Krylov.jl library on my account or on HighDimensionalEconLab?

**Comment by paulcorcuera** [comment]
> Should I fork the Krylov.jl library on my account or on HighDimensionalEconLab?

Were you able to replicate the error? I think we should have something similar to what Adam did with the Laplacians package : see [here](https://github.com/HighDimensionalEconLab/VarianceComponentsHDFE.jl/tree/main/src/laplacians). In other words, it would be better to have all the code in the VarianceComponentsHDFE repo.

**Comment by Alim-faraji** [comment]
I am waiting to use the newest version, so I can also test other things too. It seems like what Adam did is to include a minimal version of the Laplacians package into the code. I'll do the same.

**Comment by jlperla** [comment]
@paulcorcuera   @Alim-faraji  This is a tougher one than the laplacians (which we want to undo now that it is an active repo again).    Lets fork it onto the HDEL organization and have the package/manifest point to that.  Then we can beg these guys to consider a PR off of it, or move to use their competitors.  It isn't the only krylov package, but we don't want to maintain one.

**Comment by paulcorcuera** [comment]
I was trying to explore the cause of the error in these new datasets, and found the following things. Connectivity of the graph implies that the Grounded laplacian is positive definite. However, sometimes it can be close to positive semi definite (I think it happens, for example, when we have weak identification, as it is shown in Figure 1 of KSS using these datasets). This, together with some very sparse right hand sides in the exact algorithm, are causing that some error in the conjugate gradient becomes very small and negative in some iterations. The Krylov.cg algorithm attempts to take the square root of  that, and it throws the `DomainError`. 

In our medium network `test.csv`, where we never get these errors, the smallest eigenvalue of the Grounded Laplacian is between 0.15-0.35 , whereas in the Table 2 KSS data it is around 6e-9.

Maybe this is something to think about later on. Based on the discussion Adam had with the owners of the Krylov package  [here](https://github.com/JuliaSmoothOptimizers/Krylov.jl/pull/204), maybe this problem has to do with the fact that our sparse cholesky preconditioner is also close to positive semidefinite in those cases, and we can fix the preconditoner instead of modifying any line in the cg algorithm. I certainly don't understand all the math (and code) behind this, but you guys may have some ideas about what's going on. Sorry for the long post!
